[workspace]
members = ["uranium4Linux", "requester", "mine_data_strutcs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1
overflow-checks = false
debug = 2
incremental = true
debug-assertions = true